# Generated by Django 3.2.3 on 2021-07-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aportes',
            name='idRegistro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
