# Generated by Django 3.2.4 on 2021-07-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ingresos_ingresos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='ingresos',
            field=models.IntegerField(default=0),
        ),
    ]
