# Generated by Django 3.2.5 on 2021-07-13 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ingresos_ingresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('idFicha', models.AutoField(primary_key=True, serialize=False)),
                ('Medicamentos', models.CharField(max_length=30)),
                ('Cuidados_especiales', models.CharField(max_length=300)),
                ('Situación_salud', models.CharField(max_length=300)),
                ('NombreApe', models.CharField(max_length=200)),
                ('NombreCom_fam', models.CharField(max_length=200)),
                ('rutFam', models.CharField(max_length=20, null=True)),
                ('sexoFam', models.CharField(max_length=1)),
                ('fechaNa_fam', models.DateField(default=datetime.datetime.now)),
                ('Domicilio_fam', models.CharField(max_length=40)),
                ('Ocupacion_fam', models.CharField(max_length=30)),
            ],
        ),
    ]
